version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: parcel-plugin-static-files-copy
    versions:
    - 2.5.1
    - 2.6.0
  - dependency-name: "@fortawesome/fontawesome-free"
    versions:
    - 5.15.2
    - 5.15.3
  - dependency-name: parcel-bundler
    versions:
    - 1.12.5
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: bitly
    versions:
    - 7.1.2
