[build]
  publish = "build/"
  command = "yarn prod"
  functions = "lambda-build/"


[context.production]
[[redirects]]
  from ="/location/*"
  to = "https://extreme-ip-lookup.com/json/"
  status = 200



[context.deploy-preview]
[[redirects]]
  from ="/location/*"
  to = "https://extreme-ip-lookup.com/json/"
  status = 200


[context.branch-deploy]
[[redirects]]
  from ="/location/*"
  to = "https://extreme-ip-lookup.com/json/"
  status = 200