[build]
  publish = "dist/"
  command = "npm run prod"
  # functions = "lambda-build/"
  [[redirects]]
  from="/.well-known/security.txt"
  to="https://benc.io/security.txt"
  status=301
  [[redirects]]
  from="/index.html/*"
  to="/"
  status=301
  [[redirects]]
  from="/resume/*"
  to="https://resume.benc.io"
  status=301

