[build]
  publish = "build/"
  command = "yarn prod"
  functions = "lambda-build/"


[context.production]
[[redirects]]
  from="/netlify-location/*"
  to="https://extreme-ip-lookup.com/json/" 
  status=200
  [[redirects]]
  from ="/pub/*"
  to="https://pub.benc.io"
  status=301
  [[redirects]]
  from ="/geocoder/*" 
  to="https://geocode.benc.io"
  status=301
  [[redirects]]
  from ="/geocode/*"
  to="https://geocode.benc.io"
  status=301
  [[redirects]]
  from="/.well-known/security.txt"
  to="https://benc.io/security.txt"
  status=301
  [[redirects]]
  from="/resume/*"
  to="https://doc-10-5g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ggn0andi9ng1oafcec98v6c5ovcitt29/1522440000000/14645503784088162307/*/0B3UFP8Xs5x7WSlN5aUhlWjBRRWs"
  status=200
  

[context.deploy-preview]
 from="/netlify-location/*"
  to="https://extreme-ip-lookup.com/json/" 
  status=200
  [[redirects]]
  from ="/pub/*"
  to="https://pub.benc.io"
  status=301
  [[redirects]]
  from ="/geocoder/*" 
  to="https://geocode.benc.io"
  status=301
  [[redirects]]
  from ="/geocode/*"
  to="https://geocode.benc.io"
  status=301
  [[redirects]]
  from="/.well-known/security.txt"
  to="https://benc.io/security.txt"
  status=301


[context.branch-deploy]
 from="/netlify-location/*"
  to="https://extreme-ip-lookup.com/json/" 
  status=200
  [[redirects]]
  from ="/pub/*"
  to="https://pub.benc.io"
  status=301
  [[redirects]]
  from ="/geocoder/*" 
  to="https://geocode.benc.io"
  status=301
  [[redirects]]
  from ="/geocode/*"
  to="https://geocode.benc.io"
  status=301
  [[redirects]]
  from="/.well-known/security.txt"
  to="https://benc.io/security.txt"
  status=301
