/** Declaration file generated by dts-gen */
declare module "suncalc" {
  export const times: (number[])[];

  export function addTime(angle: any, riseName: any, setName: any): void;

  export function getMoonIllumination(date: any): any;

  export function getMoonPosition(date: any, lat: any, lng: any): any;

  export function getMoonTimes(date: any, lat: any, lng: any, inUTC: any): any;

  export function getPosition(date: any, lat: any, lng: any): any;

  export function getTimes(date: any, lat: any, lng: any): any;

  export namespace addTime {
    const prototype: {};
  }

  export namespace getMoonIllumination {
    const prototype: {};
  }

  export namespace getMoonPosition {
    const prototype: {};
  }

  export namespace getMoonTimes {
    const prototype: {};
  }

  export namespace getPosition {
    const prototype: {};
  }

  export namespace getTimes {
    const prototype: {};
  }
}
